// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAufOtLhXfCa2jjuHpLt7rLUZMZewoF9U',
    appId: '1:141569093069:web:66e5f072b88049f02d2884',
    messagingSenderId: '141569093069',
    projectId: 'todo-c52eb',
    authDomain: 'todo-c52eb.firebaseapp.com',
    storageBucket: 'todo-c52eb.appspot.com',
    measurementId: 'G-HXWWD5VY9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA870L1Hkcsa3_CsuhZNy44no7ggKp2VWo',
    appId: '1:141569093069:android:d6c627b1e5fad4792d2884',
    messagingSenderId: '141569093069',
    projectId: 'todo-c52eb',
    storageBucket: 'todo-c52eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBohniLwhDst96kDCz4-d2_hFM-ZPZvUPA',
    appId: '1:141569093069:ios:c99c3be41a1679462d2884',
    messagingSenderId: '141569093069',
    projectId: 'todo-c52eb',
    storageBucket: 'todo-c52eb.appspot.com',
    iosBundleId: 'com.devifitzsimmons.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBohniLwhDst96kDCz4-d2_hFM-ZPZvUPA',
    appId: '1:141569093069:ios:c99c3be41a1679462d2884',
    messagingSenderId: '141569093069',
    projectId: 'todo-c52eb',
    storageBucket: 'todo-c52eb.appspot.com',
    iosBundleId: 'com.devifitzsimmons.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAufOtLhXfCa2jjuHpLt7rLUZMZewoF9U',
    appId: '1:141569093069:web:8493e2cab8433dd72d2884',
    messagingSenderId: '141569093069',
    projectId: 'todo-c52eb',
    authDomain: 'todo-c52eb.firebaseapp.com',
    storageBucket: 'todo-c52eb.appspot.com',
    measurementId: 'G-FQL209HT6K',
  );

}